export const defaultEventConfig = {
  name: "AI Builder Finals",
  hostOrganization: "Signal Labs",
  slug: "ai-builder-finals-2026",
  type: "ai",
  mode: "hybrid",
  format: "hybrid",
  visibility: "application",
  audience: "invited",
  judgeAssignmentMode: "assigned",
  scoringMode: "weighted",
  judgingModel: "weighted",
  duration: "72 hours",
  timezone: "America/Los_Angeles",
  startDate: new Date("2026-05-14T09:00:00.000Z"),
  endDate: new Date("2026-05-17T23:00:00.000Z"),
  location: "San Francisco, CA",
  maxTeams: 48,
  teamSizeMin: 1,
  teamSizeMax: 4,
  submissionWindowHours: 4,
  allowWaitlist: true,
  allowLateEdits: false,
  requirePortfolio: false,
  requireKyc: false,
  judgeCount: 12,
  mentorCount: 6,
  tracks: ["Developer Tools", "Climate", "Healthcare", "Education"],
  participantRoles: ["Builders", "Judges", "Mentors"],
  organizerGoal:
    "Host a flexible hackathon shell that supports private cohorts, invited judges, and clean scoring operations.",
};
