export const defaultEventConfig = {
  name: "AI Builder Finals",
  hostOrganization: "Signal Labs",
  slug: "ai-builder-finals-2026",
  type: "ai",
  mode: "hybrid",
  format: "hybrid",
  visibility: "application",
  audience: "invited",
  judgeAssignmentMode: "assigned",
  scoringMode: "weighted",
  judgingModel: "weighted",
  duration: "72 hours",
  timezone: "America/Los_Angeles",
  startDate: new Date("2026-05-14T09:00:00.000Z"),
  endDate: new Date("2026-05-17T23:00:00.000Z"),
  location: "San Francisco, CA",
  maxTeams: 48,
  teamSizeMin: 1,
  teamSizeMax: 4,
  submissionWindowHours: 4,
  allowWaitlist: true,
  allowLateEdits: false,
  requirePortfolio: false,
  requireKyc: false,
  judgeCount: 12,
  mentorCount: 6,
  tracks: ["Developer Tools", "Climate", "Healthcare", "Education"],
  participantRoles: ["Builders", "Judges", "Mentors"],
  organizerGoal:
    "Host a flexible hackathon shell that supports private cohorts, invited judges, and clean scoring operations.",
};

export const sampleJudges = [
  {
    name: "Priya Raman",
    email: "priya@signaljury.dev",
    track: "Developer Tools",
    label: "Lead judge",
    code: "JUDGE-ORBIT-27",
    assignmentCapacity: 6,
  },
  {
    name: "Nina Torres",
    email: "nina@signaljury.dev",
    track: "Climate",
    label: "Track specialist",
    code: "JUDGE-TERRA-08",
    assignmentCapacity: 5,
  },
  {
    name: "Marcus Lee",
    email: "marcus@signaljury.dev",
    track: "Healthcare",
    label: "Healthcare panel",
    code: "JUDGE-CLINIC-55",
    assignmentCapacity: 5,
  },
];

export const sampleProjects = [
  {
    projectName: "Atlas Relay",
    teamName: "Northstar Labs",
    track: "Developer Tools",
    description:
      "Infrastructure copilot that turns production incidents into rollback-safe remediation plans.",
    screeningScore: 4.82,
    repoUrl: "https://github.com/example/atlas-relay",
    demoUrl: "https://example.com/demo/atlas-relay",
    submissionUrl: "https://example.com/submission/atlas-relay",
    status: "READY",
  },
  {
    projectName: "Green Grid",
    teamName: "Vector Bloom",
    track: "Climate",
    description:
      "Climate operations workspace for balancing building load against occupancy and tariff signals.",
    screeningScore: 4.76,
    repoUrl: "https://github.com/example/green-grid",
    demoUrl: "https://example.com/demo/green-grid",
    submissionUrl: "https://example.com/submission/green-grid",
    status: "READY",
  },
  {
    projectName: "ClinicFlow",
    teamName: "Octave Studio",
    track: "Healthcare",
    description:
      "Clinic workflow assistant for intake, triage, and multilingual follow-up coordination.",
    screeningScore: 4.71,
    repoUrl: "https://github.com/example/clinicflow",
    demoUrl: "",
    submissionUrl: "https://example.com/submission/clinicflow",
    status: "MISSING_VIDEO",
  },
  {
    projectName: "Lesson Loop",
    teamName: "Open Signal",
    track: "Education",
    description:
      "Teacher workspace that turns student feedback and lesson plans into differentiated follow-ups.",
    screeningScore: 4.63,
    repoUrl: "https://github.com/example/lesson-loop",
    demoUrl: "https://example.com/demo/lesson-loop",
    submissionUrl: "https://example.com/submission/lesson-loop",
    status: "READY",
  },
];
